apiVersion: v1
kind: Namespace
metadata:
  name: anil-test
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: anil-python-workload
  namespace: anil-test
  labels:
    app: anil-python
spec:
  replicas: 1
  template:
    metadata:
      labels:
          app: anil-python
    spec:
      containers:
        - name: anil-python
          image: gcr.io/GOOGLE_CLOUD_PROJECT/anil-python-test:COMMIT_SHA
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 300Mi
          ports:
          - name: python-port
            containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: anil-python-svc
  namespace: anil-test
  labels:
    app: anil-python
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: anil-python
  type: LoadBalancer

