apiVersion: v1
kind: Service
metadata:
  name: anil-python-svc
  namespace: anil-test
  labels:
    app: anil-python
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: anil-python
  type: LoadBalancer